version: '3.7'

services:
  postgres:
    image: postgres:12-alpine
    container_name: examplebot_postgres
    restart: always
    environment:
      - POSTGRES_DB=examplebot
      - POSTGRES_USER=examplebot
      - POSTGRES_PASSWORD=examplebotPa$$S
    volumes:
      - ./pgdata/:/var/lib/postgresql/data/

  app:
    build: .
    container_name: examplebot
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app/
